### PR TITLE
correct for pep8

### PR DESCRIPTION
**Pull request by eolivi**

### CODE REVIEW

**Comment by eolivi** [comment]
flake8 is ok.
pydocstyle not now..

**Comment by agramfort** [comment]
great

I'll let you iterate to complete the docstrings then.

thanks a lot

**Comment by agramfort** [comment]
perfect !

thx @eolivi 

Tyranny was not too long to endure.. :)

**Comment by eolivi** [comment]
ahahah ...
it was surprising to see how far it goes for python docstring and pep8.
line size to 80 ... is short... but okay...
Docstring: 
should not start by a space, nor a lowercase, nor by a verbs that ends with an 's' ! 
line shoud end by a '.', not a space, ...

very very constraining ... but I accept it.... it must be useful somewhere... lol

**Comment by agramfort** [comment]
conventions is the only thing that allows you to work smoothly in a
distributed group of people.

we should have the same thing for the C++ code...

**Pull request merged**
